Support ppc64le arch compilation and installation (#186)
* Update service-requirements.txt

add idna==2.10 

I met following error when build on ppc64le:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
requests 2.25.1 requires idna<3,>=2.5, but you have idna 3.6 which is incompatible.

* Update service-requirements.txt

* Update service-requirements.txt

pyyaml 6.0 is not compatible with ppc64le, downgrade to 5.4.1.

* Create 400-适配Power-ppc64le编译.md

适配Power-ppc64le编译记录

* Update service-requirements.txt

* Rename 400-适配Power-ppc64le编译.md to 400.适配Power-ppc64le编译.md

* Update 400.适配Power-ppc64le编译.md